web:
  build: .
  dockerfile: ./docker/nginx/Dockerfile-nginx
  ports:
    - "8080:80"
  links:
    - php
    - db
  volumes:
    - .:/usr/share/nginx/html/attendize
php:
  build: .
  dockerfile: ./docker/php/Dockerfile-php
  links:
    - db
    - maildev
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
php-worker:
  build: .
  dockerfile: ./docker/php/Dockerfile-php
  links:
    - db
    - maildev
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
  command: php artisan queue:work --daemon
db:
  build: .
  dockerfile: ./docker/mysql/Dockerfile-mysql
  environment:
     MYSQL_USER: attendize
     MYSQL_PASSWORD: attendize
     MYSQL_ROOT_PASSWORD: attendize
     MYSQL_DB: attendize
  ports:
    - "3333:3306"
  volumes:
    - ./docker/data/mariadb:/var/lib/mysql
maildev:
  image: djfarrelly/maildev
  ports:
    - "1080:80"
redis:
  build: .
  dockerfile: ./docker/redis/Dockerfile-redis
  volumes:
      - ./docker/data/redis:/data
